### PR TITLE
Fixing some bugs due to letter casing

### LINKED ISSUE #71: Products template bugs
Seems like the Products Template is not taking care of the letter casing of the asked URL . 

image

For Eg -  https://main--octoral--aemsites.hlx.live/es/products/non-voc/Limpiadores is breaking since the logic is trying to match "Limpiadores" with the normalized version of this keyword in the sheet. Hence we need to add a logic to normalize the asked URL first & then match.

### PR DESCRIPTION
**Pull request by meejain**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #71 

Test URLs:
- Before: https://main--octoral--aemsites.hlx.live/es/products/non-voc/Limpiadores
- After: https://issue71--octoral--aemsites.hlx.live/es/products/non-voc/Limpiadores

### CODE REVIEW

File: templates/products/products.js [hunk 1]
```diff
@@ -190,18 +190,30 @@ const groupBy = (array, key) => array.reduce((accum, current) => {
...
   // get path segments for use in product display logic
-  const [locale, products, vocCompliant, type, title] = getPathSegments();
+  const [rawLocale, rawProducts, rawVocCompliant, rawType, rawTitle] = getPathSegments();
+  if (rawLocale) { locale = normalizeString(rawLocale); }
+  if (rawProducts) { products = normalizeString(rawProducts); }
+  if (rawVocCompliant) { vocCompliant = normalizeString(rawVocCompliant); }
+  if (rawType) { type = normalizeString(rawType); }
+  if (rawTitle) { title = normalizeString(rawTitle); }
+
   const result = await fetchProducts(vocCompliant, type, title, locale, products);
```
Comment (akasjain2) [inline templates/products/products.js]: Extra argument products

File: templates/products/products.js [hunk 2]
```diff
@@ -190,18 +190,30 @@ const groupBy = (array, key) => array.reduce((accum, current) => {
   return accum;
 }, {});
 
+let locale = '';
```
Comment (akasjain2) [inline templates/products/products.js]: Since we are already passing these variables to fetchProducts, can we please move them inside decorate(doc) and avoid more global variables here?

**Review by dave-fink — APPROVED** [review]

**Review by akasjain2 — APPROVED** [review]
